import Persistence.BinaryPrefixState

/-!
# Binary Prefix Process State (deterministic state transition)

This module packages the deterministic prefix lemmas into explicit state and
step structures.  It is the last purely deterministic layer before a future
random-prefix process:

* `PrefixState r k` is a `k`-column binary prefix with a linear-independence
  certificate.
* `PrefixStep S` supplies one next column that escapes the span of `S`.
* `PrefixStep.nextState` appends that column and produces a certified
  `(k + 1)`-column independent prefix.

## What this does not prove

No random-prefix process is introduced here.  There is no sampled-column
independence theorem, conditional-probability product, random-matrix rank
probability, or Shannon achievability theorem.  This file only packages the
deterministic state transition that such later probabilistic layers will use.
-/

namespace Persistence.BinaryPrefixProcessState

open Persistence.BinaryRankGrowth

/-- A deterministic `k`-column binary prefix state, certified as linearly
independent. -/
structure PrefixState (r k : ℕ) where
  cols : Fin k → (Fin r → ZMod 2)
  independent : LinearIndependent (ZMod 2) cols

namespace PrefixState

/-- The canonical empty prefix state.  This is the deterministic starting state
for future random-prefix process layers. -/
def empty (r : ℕ) : PrefixState r 0 where
  cols := Fin.elim0
  independent := linearIndependent_empty_type

/-- The span generated by a certified prefix state. -/
def span {r k : ℕ} (S : PrefixState r k) :
    Submodule (ZMod 2) (Fin r → ZMod 2) :=
  Submodule.span (ZMod 2) (Set.range S.cols)

/-- A certified prefix state spans a subspace of rank exactly the prefix
length. -/
theorem finrank_span_eq {r k : ℕ} (S : PrefixState r k) :
    Module.finrank (ZMod 2) S.span = k := by
  unfold span
  rw [finrank_span_eq_card S.independent, Fintype.card_fin]

/-- Append a raw next column to a certified prefix state. -/
def appendCols {r k : ℕ} (S : PrefixState r k)
    (next : Fin r → ZMod 2) :
    Fin (k + 1) → (Fin r → ZMod 2) :=
  appendColumn S.cols next

end PrefixState

/-- One deterministic rank-growth step from a certified prefix state.  The
`escapes` field is the event that future probabilistic layers will assign
finite-uniform mass to. -/
structure PrefixStep {r k : ℕ} (S : PrefixState r k) where
  next : Fin r → ZMod 2
  escapes : next ∉ S.span

namespace PrefixStep

/-- The next certified prefix state obtained by appending an escaping column. -/
def nextState {r k : ℕ} {S : PrefixState r k} (T : PrefixStep S) :
    PrefixState r (k + 1) where
  cols := S.appendCols T.next
  independent :=
    linearIndependent_appendColumn_of_span_escape S.cols T.next
      S.independent (by simpa [PrefixState.span] using T.escapes)

/-- The columns of `nextState` are the original prefix columns with `T.next`
appended at the end. -/
theorem nextState_cols_eq_append {r k : ℕ} {S : PrefixState r k}
    (T : PrefixStep S) :
    T.nextState.cols = S.appendCols T.next := rfl

/-- The span of the next state has rank `k + 1`. -/
theorem finrank_nextState_span_eq {r k : ℕ} {S : PrefixState r k}
    (T : PrefixStep S) :
    Module.finrank (ZMod 2) T.nextState.span = k + 1 := by
  exact PrefixState.finrank_span_eq T.nextState

/-- Prefix-state version of the rank-growth transition: appending an escaping
column to state `S` gives a `(k + 1)`-column span. -/
theorem finrank_appendCols_span_eq_succ {r k : ℕ} {S : PrefixState r k}
    (T : PrefixStep S) :
    Module.finrank (ZMod 2)
        (Submodule.span (ZMod 2) (Set.range (S.appendCols T.next))) = k + 1 := by
  exact finrank_span_appendColumn_eq_succ_of_span_escape S.cols T.next
    S.independent (by simpa [PrefixState.span] using T.escapes)

end PrefixStep

end Persistence.BinaryPrefixProcessState
