import Persistence.ProbabilityConnection

/-!
Stochastic Collapse Time Bound
collapse time bound の stochastic 版

This module gives the probability-space version of the collapse-threshold
criterion.

For a cumulative net-action process `Aₙ(ω)`, define the pathwise survival ratio

  exp(-Aₙ(ω)).

If almost surely `Aₙ(ω) ≥ -log θ`, then almost surely the survival ratio is at
most `θ`. This is the stochastic analogue of the deterministic collapse-time
bound.
-/

open MeasureTheory

namespace Persistence.StochasticCollapseTimeBound

open Persistence.ProbabilityConnection

noncomputable section

variable {Ω : Type*} [MeasurableSpace Ω]
variable {μ : Measure Ω}

/-- Pathwise survival ratio generated by a cumulative net-action process. -/
def survivalRatioRV
    (S : StochasticExpectedProcess (μ := μ)) (n : ℕ) : Ω → ℝ :=
  fun ω => Real.exp (-S.cumulativeRV n ω)

/-- Almost-sure collapse below the fraction `θ` by time `n`. -/
def CollapseAlmostSurely
    (S : StochasticExpectedProcess (μ := μ)) (n : ℕ) (θ : ℝ) : Prop :=
  ∀ᵐ ω ∂μ, survivalRatioRV S n ω ≤ θ

/-- Pathwise threshold crossing in cumulative net action forces pathwise collapse
of the survival ratio. -/
theorem survivalRatio_le_of_threshold_ae
    (S : StochasticExpectedProcess (μ := μ)) (n : ℕ)
    {θ : ℝ} (hθ : 0 < θ)
    (hA : ∀ᵐ ω ∂μ, -Real.log θ ≤ S.cumulativeRV n ω) :
    ∀ᵐ ω ∂μ, survivalRatioRV S n ω ≤ θ := by
  filter_upwards [hA] with ω hω
  dsimp [survivalRatioRV]
  have hexp : Real.exp (-S.cumulativeRV n ω) ≤ Real.exp (Real.log θ) := by
    exact (Real.exp_le_exp).2 (by linarith)
  simpa [Real.exp_log hθ] using hexp

/-- Stochastic collapse-time bound:
almost-sure threshold crossing implies almost-sure collapse below `θ`. -/
theorem collapseAlmostSurely_of_threshold_ae
    (S : StochasticExpectedProcess (μ := μ)) (n : ℕ)
    {θ : ℝ} (hθ : 0 < θ)
    (hA : ∀ᵐ ω ∂μ, -Real.log θ ≤ S.cumulativeRV n ω) :
    CollapseAlmostSurely S n θ :=
  survivalRatio_le_of_threshold_ae S n hθ hA

end

end Persistence.StochasticCollapseTimeBound
