import Persistence.StructuralPersistenceG1ObservationalCore

/-!
# G1 Current-View Response Completeness

This module isolates the non-horizontal current-view response bottleneck.

The point is deliberately narrow: instead of adding another route that assumes
`CurrentViewResponseImageComplete`, we state observational hypotheses under
which that completeness condition follows.  The extra hypothesis is visible:
global response-image inclusion by current view must be paired with target-side
current-view response-image extensionality.
-/

namespace Persistence.StructuralPersistence

universe u v w x y

/--
Response images are determined by the current observable view of a process.

If two states of the same process have the same current observable view, every
one-step response available from the first state is also available from the
second.  This is a role-free observational extensionality condition; it names
the extra stability needed to turn global view/response image information into
pointwise same-current-view completeness.
-/
def CurrentViewResponseImageExtensional
    {State : Type u} {Action : Type v} {Observation : Type w}
    (P : ObservationalPersistenceProcess State Action Observation) : Prop :=
  forall {sourceState targetState : State},
    P.currentView targetState = P.currentView sourceState ->
      ResponseImagePreservationAt P P sourceState targetState

/--
If the current observable view determines the state, then one-step response
images are current-view extensional.

This is the visible-state route: no hidden state remains behind the current
view, so moving a response from one same-view state to another is just
transport along equality of states.
-/
theorem currentViewResponseImageExtensional_of_injective_currentView
    {State : Type u} {Action : Type v} {Observation : Type w}
    (P : ObservationalPersistenceProcess State Action Observation)
    (hinjective : Function.Injective P.currentView) :
    CurrentViewResponseImageExtensional P := by
  intro sourceState targetState hview response hsource
  have hstate : sourceState = targetState := hinjective hview.symm
  subst sourceState
  exact hsource

/--
Local current-view one-step extensionality makes one-step response images
current-view extensional.

This is weaker than visible-state injectivity: hidden same-current-view states
may remain, but if every action has the same observable response from them,
then a response observed from one such state is also observed from the other.
-/
theorem currentViewResponseImageExtensional_of_oneStepExtensional
    {State : Type u} {Action : Type v} {Observation : Type w}
    (P : ObservationalPersistenceProcess State Action Observation)
    (oneStep : CurrentViewOneStepExtensional P) :
    CurrentViewResponseImageExtensional P := by
  intro sourceState targetState hview response hsource
  rcases hsource with ⟨action, hresponse⟩
  exact ⟨action, (oneStep hview.symm action).symm.trans hresponse⟩

/--
Global response-image inclusion indexed by current observable view.

Every response produced by the source process from some state with a given
current view is produced by the target process from some state with the same
current view.  This is weaker than `CurrentViewResponseImageComplete`: it does
not say the response is available from every target state with that view.
-/
def CurrentViewGlobalResponseImageIncluded
    {StateA : Type u} {ActionA : Type v} {Observation : Type w}
    {StateB : Type x} {ActionB : Type y}
    (A : ObservationalPersistenceProcess StateA ActionA Observation)
    (B : ObservationalPersistenceProcess StateB ActionB Observation) : Prop :=
  forall view response,
    (∃ sourceState : StateA,
      A.currentView sourceState = view ∧
        ∃ sourceAction : ActionA,
          A.response sourceState sourceAction = response) ->
      ∃ targetState : StateB,
        B.currentView targetState = view ∧
          ∃ targetAction : ActionB,
            B.response targetState targetAction = response

/--
Bidirectional global response-image equality by current observable view.

This is still only a global image statement.  To obtain pointwise
same-current-view response-image completeness, the target side must also be
current-view response-image extensional.
-/
def CurrentViewGlobalResponseImageEquivalent
    {StateA : Type u} {ActionA : Type v} {Observation : Type w}
    {StateB : Type x} {ActionB : Type y}
    (A : ObservationalPersistenceProcess StateA ActionA Observation)
    (B : ObservationalPersistenceProcess StateB ActionB Observation) : Prop :=
  CurrentViewGlobalResponseImageIncluded A B ∧
    CurrentViewGlobalResponseImageIncluded B A

/--
Global trace-log language inclusion indexed by current observable view.

Every finite prefix log generated by the source process from some state with a
given current view is generated by the target process from some state with the
same current view.  This is weaker than
`CurrentViewTraceLogLanguageIncluded`: it does not say the log is available
from every target state with that view.
-/
def CurrentViewGlobalTraceLogLanguageIncluded
    {StateA : Type u} {ActionA : Type v} {Observation : Type w}
    {StateB : Type x} {ActionB : Type y}
    (A : ObservationalPersistenceProcess StateA ActionA Observation)
    (B : ObservationalPersistenceProcess StateB ActionB Observation) : Prop :=
  forall view log,
    (∃ sourceState : StateA,
      A.currentView sourceState = view ∧
        TraceLogLanguageAt A sourceState log) ->
      ∃ targetState : StateB,
        B.currentView targetState = view ∧
          TraceLogLanguageAt B targetState log

/--
Bidirectional global trace-log language equality by current observable view.

As with the response-image version, this is still a global image statement.
Target-side trace-log extensionality is needed before it becomes pointwise
same-current-view trace-log language inclusion.
-/
def CurrentViewGlobalTraceLogLanguageEquivalent
    {StateA : Type u} {ActionA : Type v} {Observation : Type w}
    {StateB : Type x} {ActionB : Type y}
    (A : ObservationalPersistenceProcess StateA ActionA Observation)
    (B : ObservationalPersistenceProcess StateB ActionB Observation) : Prop :=
  CurrentViewGlobalTraceLogLanguageIncluded A B ∧
    CurrentViewGlobalTraceLogLanguageIncluded B A

variable {StateA : Type u} {ActionA : Type v} {Observation : Type w}
variable {StateB : Type x} {ActionB : Type y}
variable {A : ObservationalPersistenceProcess StateA ActionA Observation}
variable {B : ObservationalPersistenceProcess StateB ActionB Observation}

/--
Global current-view response-image inclusion plus target-side extensionality
derives current-view response-image completeness.

This is the bottleneck theorem: a global observable image inclusion only gives
a matching target state with the same current view.  To use an arbitrary target
state with that view, the target process must make one-step response images
extensional in the current view.
-/
theorem currentViewResponseImageComplete_of_globalResponseImageIncluded
    (included : CurrentViewGlobalResponseImageIncluded A B)
    (targetExtensional : CurrentViewResponseImageExtensional B) :
    CurrentViewResponseImageComplete A B := by
  intro sourceState targetState hview response hsource
  rcases hsource with ⟨sourceAction, hresponse⟩
  rcases
      included (A.currentView sourceState) response
        ⟨sourceState, rfl, sourceAction, hresponse⟩ with
    ⟨witnessTargetState, hwitnessView, targetAction, htargetResponse⟩
  exact
    targetExtensional
      (sourceState := witnessTargetState)
      (targetState := targetState)
      (hview.trans hwitnessView.symm)
      response
      ⟨targetAction, htargetResponse⟩

/--
Global current-view response-image inclusion plus target-side local one-step
stability derives current-view response-image completeness.

The one-step condition is used only to supply the response-image extensionality
needed by the global-to-local fold; the global image hypothesis remains an
explicit input.
-/
theorem currentViewResponseImageComplete_of_globalResponseImageIncluded_of_oneStep
    (included : CurrentViewGlobalResponseImageIncluded A B)
    (targetOneStep : CurrentViewOneStepExtensional B) :
    CurrentViewResponseImageComplete A B :=
  currentViewResponseImageComplete_of_globalResponseImageIncluded
    included
    (currentViewResponseImageExtensional_of_oneStepExtensional
      B targetOneStep)

/--
Global current-view response-image inclusion plus target-side extensionality
rules out a local current-view response-image gap.

This is the gap-form consequence of
`currentViewResponseImageComplete_of_globalResponseImageIncluded`.
-/
theorem no_currentViewResponseImageGap_of_globalResponseImageIncluded
    (included : CurrentViewGlobalResponseImageIncluded A B)
    (targetExtensional : CurrentViewResponseImageExtensional B) :
    ¬ CurrentViewResponseImageGap A B :=
  no_currentViewResponseImageGap_of_currentViewResponseImageComplete
    (currentViewResponseImageComplete_of_globalResponseImageIncluded
      included targetExtensional)

/--
Global current-view response-image inclusion plus target-side local one-step
stability rules out a local current-view response-image gap.
-/
theorem no_currentViewResponseImageGap_of_globalResponseImageIncluded_of_oneStep
    (included : CurrentViewGlobalResponseImageIncluded A B)
    (targetOneStep : CurrentViewOneStepExtensional B) :
    ¬ CurrentViewResponseImageGap A B :=
  no_currentViewResponseImageGap_of_currentViewResponseImageComplete
    (currentViewResponseImageComplete_of_globalResponseImageIncluded_of_oneStep
      included targetOneStep)

/--
If global current-view response-image inclusion holds but a local current-view
response-image gap remains, then target-side current-view response-image
extensionality cannot hold.

This is the deletion form for the extensionality hypothesis: the global image
condition can find some target state with the right current view, but without
target-side extensionality the chosen target state may still miss the response.
-/
theorem not_currentViewResponseImageExtensional_of_globalResponseImageIncluded_gap
    (included : CurrentViewGlobalResponseImageIncluded A B)
    (gap : CurrentViewResponseImageGap A B) :
    ¬ CurrentViewResponseImageExtensional B := by
  intro targetExtensional
  exact
    not_currentViewResponseImageComplete_of_currentViewResponseImageGap
      gap
      (currentViewResponseImageComplete_of_globalResponseImageIncluded
        included targetExtensional)

/--
Bidirectional global response-image equivalence plus current-view
extensionality on both processes gives bidirectional current-view
response-image completeness.

This is not arbitrary-adapter discovery and it does not choose fixed action
translators.  It records the exact observational conditions under which the
previously supplied current-view completeness bottleneck follows.
-/
theorem currentViewResponseImageEquivalent_of_globalResponseImageEquivalent
    (equivalent : CurrentViewGlobalResponseImageEquivalent A B)
    (sourceExtensional : CurrentViewResponseImageExtensional A)
    (targetExtensional : CurrentViewResponseImageExtensional B) :
    CurrentViewResponseImageEquivalent A B :=
  ⟨currentViewResponseImageComplete_of_globalResponseImageIncluded
      equivalent.1 targetExtensional,
    currentViewResponseImageComplete_of_globalResponseImageIncluded
      equivalent.2 sourceExtensional⟩

/--
Bidirectional global response-image equivalence becomes local same-current-view
response-image equivalence when both current views determine their states.

This is the visible-state structural route into the scoped entrance: no hidden
same-view state can carry a different one-step response image on either side.
-/
theorem currentViewResponseImageEquivalent_of_globalResponseImageEquivalent_of_injective_currentView
    (equivalent : CurrentViewGlobalResponseImageEquivalent A B)
    (sourceInjective : Function.Injective A.currentView)
    (targetInjective : Function.Injective B.currentView) :
    CurrentViewResponseImageEquivalent A B :=
  currentViewResponseImageEquivalent_of_globalResponseImageEquivalent
    equivalent
    (currentViewResponseImageExtensional_of_injective_currentView
      A sourceInjective)
    (currentViewResponseImageExtensional_of_injective_currentView
      B targetInjective)

/--
Bidirectional global response-image equivalence becomes local same-current-view
response-image equivalence when both processes are locally one-step
extensional by current view.

This is weaker than the visible-state route: current views need not determine
states, but hidden same-view states must have the same observable one-step
responses.
-/
theorem currentViewResponseImageEquivalent_of_globalResponseImageEquivalent_of_oneStep
    (equivalent : CurrentViewGlobalResponseImageEquivalent A B)
    (sourceOneStep : CurrentViewOneStepExtensional A)
    (targetOneStep : CurrentViewOneStepExtensional B) :
    CurrentViewResponseImageEquivalent A B :=
  currentViewResponseImageEquivalent_of_globalResponseImageEquivalent
    equivalent
    (currentViewResponseImageExtensional_of_oneStepExtensional
      A sourceOneStep)
    (currentViewResponseImageExtensional_of_oneStepExtensional
      B targetOneStep)

/--
Global current-view trace-log language inclusion plus target-side trace-log
extensionality derives pointwise current-view trace-log language inclusion.

The global language condition may realize a source log from some target state
with the right current view.  The extensionality condition moves that log to
the selected target state with the same current view.
-/
theorem currentViewTraceLogLanguageIncluded_of_globalTraceLogLanguageIncluded
    (included : CurrentViewGlobalTraceLogLanguageIncluded A B)
    (targetExtensional : CurrentViewTraceLogExtensional B) :
    CurrentViewTraceLogLanguageIncluded A B := by
  intro sourceState targetState hview log hsource
  rcases
      included (A.currentView sourceState) log
        ⟨sourceState, rfl, hsource⟩ with
    ⟨witnessTargetState, hwitnessView, hwitnessLog⟩
  rcases hwitnessLog with ⟨targetActions, htargetLog⟩
  have hsameView :
      B.currentView witnessTargetState =
        B.currentView targetState :=
    hwitnessView.trans hview.symm
  exact
    ⟨targetActions,
      (targetExtensional hsameView targetActions).symm.trans htargetLog⟩

/--
Global current-view trace-log language inclusion plus target-side local
one-step stability derives pointwise current-view trace-log language inclusion.

The one-step condition supplies current-view trace-log extensionality by
finite-prefix induction.
-/
theorem currentViewTraceLogLanguageIncluded_of_globalTraceLogLanguageIncluded_of_oneStep
    (included : CurrentViewGlobalTraceLogLanguageIncluded A B)
    (targetOneStep : CurrentViewOneStepExtensional B) :
    CurrentViewTraceLogLanguageIncluded A B :=
  currentViewTraceLogLanguageIncluded_of_globalTraceLogLanguageIncluded
    included
    (currentViewTraceLogExtensional_of_oneStepExtensional
      B targetOneStep)

/--
Bidirectional global current-view trace-log language equivalence plus
trace-log extensionality on both processes gives bidirectional pointwise
current-view trace-log language equivalence.

This remains an observational scope theorem: it does not derive target
selection, action translators, or structural-persistence roles.
-/
theorem currentViewTraceLogLanguageEquivalent_of_globalTraceLogLanguageEquivalent
    (equivalent : CurrentViewGlobalTraceLogLanguageEquivalent A B)
    (sourceExtensional : CurrentViewTraceLogExtensional A)
    (targetExtensional : CurrentViewTraceLogExtensional B) :
    CurrentViewTraceLogLanguageEquivalent A B := by
  intro sourceState targetState hview log
  constructor
  · exact
      (currentViewTraceLogLanguageIncluded_of_globalTraceLogLanguageIncluded
        equivalent.1 targetExtensional)
        hview log
  · exact
      (currentViewTraceLogLanguageIncluded_of_globalTraceLogLanguageIncluded
        equivalent.2 sourceExtensional)
        hview.symm log

/--
Bidirectional global current-view trace-log language equivalence plus local
one-step stability on both processes gives bidirectional pointwise
current-view trace-log language equivalence.
-/
theorem currentViewTraceLogLanguageEquivalent_of_globalTraceLogLanguageEquivalent_of_oneStep
    (equivalent : CurrentViewGlobalTraceLogLanguageEquivalent A B)
    (sourceOneStep : CurrentViewOneStepExtensional A)
    (targetOneStep : CurrentViewOneStepExtensional B) :
    CurrentViewTraceLogLanguageEquivalent A B :=
  currentViewTraceLogLanguageEquivalent_of_globalTraceLogLanguageEquivalent
    equivalent
    (currentViewTraceLogExtensional_of_oneStepExtensional
      A sourceOneStep)
    (currentViewTraceLogExtensional_of_oneStepExtensional
      B targetOneStep)

/--
A source-covered role-free response-image simulation gives global
current-view response-image inclusion.

The relation and coverage are still supplied: this theorem only turns those
observational inputs into the global image condition consumed by the
current-view-extensional entrance.  It does not derive the simulation from
arbitrary alternative admissibility.
-/
theorem currentViewGlobalResponseImageIncluded_of_responseImageSimulation_sourceCovered
    (simulation : ObservationalResponseImageSimulation A B)
    (sourceCovered :
      forall sourceState : StateA,
        ∃ targetState : StateB,
          simulation.related sourceState targetState) :
    CurrentViewGlobalResponseImageIncluded A B := by
  intro view response hsource
  rcases hsource with
    ⟨sourceState, hsourceView, sourceAction, hsourceResponse⟩
  rcases sourceCovered sourceState with ⟨targetState, hrelated⟩
  have htargetView : B.currentView targetState = view :=
    (simulation.preserves_currentView hrelated).trans hsourceView
  rcases
      simulation.responseImagePreservationAt hrelated response
        ⟨sourceAction, hsourceResponse⟩ with
    ⟨targetAction, htargetResponse⟩
  exact ⟨targetState, htargetView, targetAction, htargetResponse⟩

/--
A source-covered role-free response-image simulation also gives global
current-view trace-log language inclusion.

The finite target trace is built by the simulation's existential one-step
closure induction; no fixed action translator or Structural Persistence role
is introduced here.
-/
theorem currentViewGlobalTraceLogLanguageIncluded_of_responseImageSimulation_sourceCovered
    (simulation : ObservationalResponseImageSimulation A B)
    (sourceCovered :
      forall sourceState : StateA,
        ∃ targetState : StateB,
          simulation.related sourceState targetState) :
    CurrentViewGlobalTraceLogLanguageIncluded A B := by
  intro view log hsource
  rcases hsource with ⟨sourceState, hsourceView, actions, hsourceLog⟩
  rcases sourceCovered sourceState with ⟨targetState, hrelated⟩
  have htargetView : B.currentView targetState = view :=
    (simulation.preserves_currentView hrelated).trans hsourceView
  rcases simulation.traceLogImagePreservationAt hrelated actions with
    ⟨targetActions, htargetLog⟩
  exact ⟨targetState, htargetView, targetActions, htargetLog.trans hsourceLog⟩

/--
A source-covered trace simulation gives global current-view response-image
inclusion by taking the translated source action as the target witness.

This is the fixed-translator version of the source-covered simulation route.
The translator and relation remain explicit inputs.
-/
theorem currentViewGlobalResponseImageIncluded_of_traceSimulation_sourceCovered
    (simulation : ObservationalTraceSimulation A B)
    (sourceCovered :
      forall sourceState : StateA,
        ∃ targetState : StateB,
          simulation.related sourceState targetState) :
    CurrentViewGlobalResponseImageIncluded A B := by
  intro view response hsource
  rcases hsource with
    ⟨sourceState, hsourceView, sourceAction, hsourceResponse⟩
  rcases sourceCovered sourceState with ⟨targetState, hrelated⟩
  have htargetView : B.currentView targetState = view :=
    (simulation.preserves_currentView hrelated).trans hsourceView
  exact
    ⟨targetState, htargetView, simulation.toAction sourceAction,
      (simulation.preserves_response hrelated sourceAction).trans
        hsourceResponse⟩

/--
A source-covered trace simulation gives global current-view trace-log language
inclusion.

This moves from a local related-state simulation to a global view-indexed
language statement, while keeping the coverage hypothesis visible.
-/
theorem currentViewGlobalTraceLogLanguageIncluded_of_traceSimulation_sourceCovered
    (simulation : ObservationalTraceSimulation A B)
    (sourceCovered :
      forall sourceState : StateA,
        ∃ targetState : StateB,
          simulation.related sourceState targetState) :
    CurrentViewGlobalTraceLogLanguageIncluded A B := by
  intro view log hsource
  rcases hsource with ⟨sourceState, hsourceView, actions, hsourceLog⟩
  rcases sourceCovered sourceState with ⟨targetState, hrelated⟩
  have htargetView : B.currentView targetState = view :=
    (simulation.preserves_currentView hrelated).trans hsourceView
  exact
    ⟨targetState, htargetView, actions.map simulation.toAction,
      (simulation.preserves_traceLog hrelated actions).symm.trans
        hsourceLog⟩

/--
A transition-preserving map gives global current-view response-image
inclusion.

This is still a supplied-map route: the state/action translation and step
commutation live in `phi`.
-/
theorem currentViewGlobalResponseImageIncluded_of_transitionMap
    (phi : ObservationalTransitionMap A B) :
    CurrentViewGlobalResponseImageIncluded A B :=
  currentViewGlobalResponseImageIncluded_of_traceSimulation_sourceCovered
    (ObservationalTraceSimulation.ofTransitionMap phi)
    (fun sourceState => ⟨phi.toState sourceState, rfl⟩)

/--
A transition-preserving map gives global current-view trace-log language
inclusion.

This packages the induction theorem for transition maps into the global
view-indexed language surface.
-/
theorem currentViewGlobalTraceLogLanguageIncluded_of_transitionMap
    (phi : ObservationalTransitionMap A B) :
    CurrentViewGlobalTraceLogLanguageIncluded A B :=
  currentViewGlobalTraceLogLanguageIncluded_of_traceSimulation_sourceCovered
    (ObservationalTraceSimulation.ofTransitionMap phi)
    (fun sourceState => ⟨phi.toState sourceState, rfl⟩)

/--
Bidirectional source-covered response-image simulations give global
current-view response-image equivalence.

This is still a simulation/coverage theorem: the forward and reverse
relations, together with their source-coverage witnesses, remain explicit
inputs.
-/
theorem currentViewGlobalResponseImageEquivalent_of_responseImageSimulations_sourceCovered
    (forward : ObservationalResponseImageSimulation A B)
    (reverse : ObservationalResponseImageSimulation B A)
    (forwardCovered :
      forall sourceState : StateA,
        ∃ targetState : StateB,
          forward.related sourceState targetState)
    (reverseCovered :
      forall targetState : StateB,
        ∃ sourceState : StateA,
          reverse.related targetState sourceState) :
    CurrentViewGlobalResponseImageEquivalent A B :=
  ⟨currentViewGlobalResponseImageIncluded_of_responseImageSimulation_sourceCovered
      forward forwardCovered,
    currentViewGlobalResponseImageIncluded_of_responseImageSimulation_sourceCovered
      reverse reverseCovered⟩

/--
Bidirectional source-covered response-image simulations give global
current-view trace-log language equivalence.

The finite trace witnesses are still built from the supplied response-image
simulation inductions in each direction.
-/
theorem currentViewGlobalTraceLogLanguageEquivalent_of_responseImageSimulations_sourceCovered
    (forward : ObservationalResponseImageSimulation A B)
    (reverse : ObservationalResponseImageSimulation B A)
    (forwardCovered :
      forall sourceState : StateA,
        ∃ targetState : StateB,
          forward.related sourceState targetState)
    (reverseCovered :
      forall targetState : StateB,
        ∃ sourceState : StateA,
          reverse.related targetState sourceState) :
    CurrentViewGlobalTraceLogLanguageEquivalent A B :=
  ⟨currentViewGlobalTraceLogLanguageIncluded_of_responseImageSimulation_sourceCovered
      forward forwardCovered,
    currentViewGlobalTraceLogLanguageIncluded_of_responseImageSimulation_sourceCovered
      reverse reverseCovered⟩

/--
Bidirectional source-covered trace simulations give global current-view
response-image equivalence.

This is the fixed-translator variant of the bidirectional simulation route.
-/
theorem currentViewGlobalResponseImageEquivalent_of_traceSimulations_sourceCovered
    (forward : ObservationalTraceSimulation A B)
    (reverse : ObservationalTraceSimulation B A)
    (forwardCovered :
      forall sourceState : StateA,
        ∃ targetState : StateB,
          forward.related sourceState targetState)
    (reverseCovered :
      forall targetState : StateB,
        ∃ sourceState : StateA,
          reverse.related targetState sourceState) :
    CurrentViewGlobalResponseImageEquivalent A B :=
  ⟨currentViewGlobalResponseImageIncluded_of_traceSimulation_sourceCovered
      forward forwardCovered,
    currentViewGlobalResponseImageIncluded_of_traceSimulation_sourceCovered
      reverse reverseCovered⟩

/--
Bidirectional source-covered trace simulations give global current-view
trace-log language equivalence.
-/
theorem currentViewGlobalTraceLogLanguageEquivalent_of_traceSimulations_sourceCovered
    (forward : ObservationalTraceSimulation A B)
    (reverse : ObservationalTraceSimulation B A)
    (forwardCovered :
      forall sourceState : StateA,
        ∃ targetState : StateB,
          forward.related sourceState targetState)
    (reverseCovered :
      forall targetState : StateB,
        ∃ sourceState : StateA,
          reverse.related targetState sourceState) :
    CurrentViewGlobalTraceLogLanguageEquivalent A B :=
  ⟨currentViewGlobalTraceLogLanguageIncluded_of_traceSimulation_sourceCovered
      forward forwardCovered,
    currentViewGlobalTraceLogLanguageIncluded_of_traceSimulation_sourceCovered
      reverse reverseCovered⟩

/--
Transition-preserving maps in both directions give global current-view
response-image equivalence.

The maps are still supplied; this theorem only bundles their induced global
image inclusions.
-/
theorem currentViewGlobalResponseImageEquivalent_of_transitionMaps
    (forward : ObservationalTransitionMap A B)
    (reverse : ObservationalTransitionMap B A) :
    CurrentViewGlobalResponseImageEquivalent A B :=
  ⟨currentViewGlobalResponseImageIncluded_of_transitionMap forward,
    currentViewGlobalResponseImageIncluded_of_transitionMap reverse⟩

/--
Transition-preserving maps in both directions give global current-view
trace-log language equivalence.
-/
theorem currentViewGlobalTraceLogLanguageEquivalent_of_transitionMaps
    (forward : ObservationalTransitionMap A B)
    (reverse : ObservationalTransitionMap B A) :
    CurrentViewGlobalTraceLogLanguageEquivalent A B :=
  ⟨currentViewGlobalTraceLogLanguageIncluded_of_transitionMap forward,
    currentViewGlobalTraceLogLanguageIncluded_of_transitionMap reverse⟩

/-!
Toy counterexample showing that global response-image inclusion alone is not
current-view response-image completeness.

The target process has two states with the same current observable view.  One
state realizes the source response image; the other does not.  Thus global
view-indexed inclusion holds, but pointwise same-current-view completeness
fails exactly where target-side extensionality fails.
-/
namespace CurrentViewResponseCompletenessCounterexample

inductive SourceState where
  | start
  | next
  deriving DecidableEq, Repr

inductive TargetState where
  | good
  | bad
  | next
  deriving DecidableEq, Repr

def sourceObserve : SourceState -> Bool
  | .start => false
  | .next => true

def sourceStep : SourceState -> Unit -> SourceState
  | _, _ => .next

def sourceProcess :
    ObservationalPersistenceProcess SourceState Unit Bool where
  observe := sourceObserve
  step := sourceStep
  readout := fun _ => BoundaryStatus.viable

def targetObserve : TargetState -> Bool
  | .good => false
  | .bad => false
  | .next => true

def targetStep : TargetState -> Unit -> TargetState
  | .good, _ => .next
  | .bad, _ => .bad
  | .next, _ => .next

def targetProcess :
    ObservationalPersistenceProcess TargetState Unit Bool where
  observe := targetObserve
  step := targetStep
  readout := fun _ => BoundaryStatus.viable

theorem globalResponseImageIncluded :
    CurrentViewGlobalResponseImageIncluded
      sourceProcess targetProcess := by
  intro view response hsource
  rcases hsource with ⟨sourceState, hview, sourceAction, hresponse⟩
  cases sourceState <;> cases sourceAction
  · cases hview
    cases hresponse
    exact ⟨TargetState.good, rfl, (), rfl⟩
  · cases hview
    cases hresponse
    exact ⟨TargetState.next, rfl, (), rfl⟩

theorem target_not_currentViewResponseImageExtensional :
    ¬ CurrentViewResponseImageExtensional targetProcess := by
  intro extensional
  have hpreserve :
      ResponseImagePreservationAt
        targetProcess targetProcess TargetState.good TargetState.bad :=
    extensional (sourceState := TargetState.good)
      (targetState := TargetState.bad) rfl
  rcases hpreserve
      (targetProcess.response TargetState.good ())
      ⟨(), rfl⟩ with
    ⟨targetAction, htarget⟩
  cases targetAction
  cases htarget

theorem not_currentViewResponseImageComplete :
    ¬ CurrentViewResponseImageComplete sourceProcess targetProcess := by
  intro complete
  have hpreserve :
      ResponseImagePreservationAt
        sourceProcess targetProcess SourceState.start TargetState.bad :=
    complete (sA := SourceState.start) (sB := TargetState.bad) rfl
  rcases hpreserve
      (sourceProcess.response SourceState.start ())
      ⟨(), rfl⟩ with
    ⟨targetAction, htarget⟩
  cases targetAction
  cases htarget

/--
Global current-view response-image inclusion can hold while current-view
response-image completeness fails.

This is the deletion test for the extensionality hypothesis in
`currentViewResponseImageComplete_of_globalResponseImageIncluded`: the global
image condition gives a matching target state, but not every target state with
the same current view has the same response image.
-/
theorem globalResponseImageIncluded_not_enough_for_completeness :
    CurrentViewGlobalResponseImageIncluded sourceProcess targetProcess ∧
      ¬ CurrentViewResponseImageComplete sourceProcess targetProcess :=
  ⟨globalResponseImageIncluded, not_currentViewResponseImageComplete⟩

end CurrentViewResponseCompletenessCounterexample

/-!
A stronger counterexample: bidirectional global current-view response-image
equivalence still does not imply pointwise current-view response-image
completeness without current-view response-image extensionality.

Both processes have the same global response image at the shared current view,
but each process has two same-current-view states with different one-step
response images.  Thus global image equivalence is too coarse to be the
arbitrary-alternative admissibility condition by itself.
-/
namespace BidirectionalGlobalResponseEquivalenceCounterexample

inductive SourceState where
  | high
  | low
  | nextHigh
  | nextLow
  deriving DecidableEq, Repr

inductive TargetState where
  | high
  | low
  | nextHigh
  | nextLow
  deriving DecidableEq, Repr

def sourceObserve : SourceState -> Bool
  | .high => false
  | .low => false
  | .nextHigh => true
  | .nextLow => false

def sourceStep : SourceState -> Unit -> SourceState
  | .high, _ => .nextHigh
  | .low, _ => .nextLow
  | .nextHigh, _ => .nextHigh
  | .nextLow, _ => .nextLow

def sourceProcess :
    ObservationalPersistenceProcess SourceState Unit Bool where
  observe := sourceObserve
  step := sourceStep
  readout := fun _ => BoundaryStatus.viable

def targetObserve : TargetState -> Bool
  | .high => false
  | .low => false
  | .nextHigh => true
  | .nextLow => false

def targetStep : TargetState -> Unit -> TargetState
  | .high, _ => .nextHigh
  | .low, _ => .nextLow
  | .nextHigh, _ => .nextHigh
  | .nextLow, _ => .nextLow

def targetProcess :
    ObservationalPersistenceProcess TargetState Unit Bool where
  observe := targetObserve
  step := targetStep
  readout := fun _ => BoundaryStatus.viable

theorem globalResponseImageIncluded_forward :
    CurrentViewGlobalResponseImageIncluded
      sourceProcess targetProcess := by
  intro view response hsource
  rcases hsource with ⟨sourceState, hview, sourceAction, hresponse⟩
  cases sourceState <;> cases sourceAction
  · cases hview
    cases hresponse
    exact ⟨TargetState.high, rfl, (), rfl⟩
  · cases hview
    cases hresponse
    exact ⟨TargetState.low, rfl, (), rfl⟩
  · cases hview
    cases hresponse
    exact ⟨TargetState.nextHigh, rfl, (), rfl⟩
  · cases hview
    cases hresponse
    exact ⟨TargetState.nextLow, rfl, (), rfl⟩

theorem globalResponseImageIncluded_reverse :
    CurrentViewGlobalResponseImageIncluded
      targetProcess sourceProcess := by
  intro view response htarget
  rcases htarget with ⟨targetState, hview, targetAction, hresponse⟩
  cases targetState <;> cases targetAction
  · cases hview
    cases hresponse
    exact ⟨SourceState.high, rfl, (), rfl⟩
  · cases hview
    cases hresponse
    exact ⟨SourceState.low, rfl, (), rfl⟩
  · cases hview
    cases hresponse
    exact ⟨SourceState.nextHigh, rfl, (), rfl⟩
  · cases hview
    cases hresponse
    exact ⟨SourceState.nextLow, rfl, (), rfl⟩

theorem globalResponseImageEquivalent :
    CurrentViewGlobalResponseImageEquivalent
      sourceProcess targetProcess :=
  ⟨globalResponseImageIncluded_forward,
    globalResponseImageIncluded_reverse⟩

theorem source_not_currentViewResponseImageExtensional :
    ¬ CurrentViewResponseImageExtensional sourceProcess := by
  intro extensional
  have hpreserve :
      ResponseImagePreservationAt
        sourceProcess sourceProcess SourceState.high SourceState.low :=
    extensional (sourceState := SourceState.high)
      (targetState := SourceState.low) rfl
  rcases hpreserve
      (sourceProcess.response SourceState.high ())
      ⟨(), rfl⟩ with
    ⟨sourceAction, hsource⟩
  cases sourceAction
  cases hsource

theorem target_not_currentViewResponseImageExtensional :
    ¬ CurrentViewResponseImageExtensional targetProcess := by
  intro extensional
  have hpreserve :
      ResponseImagePreservationAt
        targetProcess targetProcess TargetState.high TargetState.low :=
    extensional (sourceState := TargetState.high)
      (targetState := TargetState.low) rfl
  rcases hpreserve
      (targetProcess.response TargetState.high ())
      ⟨(), rfl⟩ with
    ⟨targetAction, htarget⟩
  cases targetAction
  cases htarget

theorem not_currentViewResponseImageComplete :
    ¬ CurrentViewResponseImageComplete sourceProcess targetProcess := by
  intro complete
  have hpreserve :
      ResponseImagePreservationAt
        sourceProcess targetProcess SourceState.high TargetState.low :=
    complete (sA := SourceState.high) (sB := TargetState.low) rfl
  rcases hpreserve
      (sourceProcess.response SourceState.high ())
      ⟨(), rfl⟩ with
    ⟨targetAction, htarget⟩
  cases targetAction
  cases htarget

/--
Bidirectional global current-view response-image equivalence alone does not
imply pointwise current-view response-image completeness.
-/
theorem globalResponseImageEquivalent_not_enough_for_completeness :
    CurrentViewGlobalResponseImageEquivalent sourceProcess targetProcess ∧
      ¬ CurrentViewResponseImageComplete sourceProcess targetProcess :=
  ⟨globalResponseImageEquivalent, not_currentViewResponseImageComplete⟩

/--
Bidirectional global current-view response-image equivalence alone does not
imply bidirectional pointwise current-view response-image equivalence.
-/
theorem globalResponseImageEquivalent_not_enough_for_responseImageEquivalent :
    CurrentViewGlobalResponseImageEquivalent sourceProcess targetProcess ∧
      ¬ CurrentViewResponseImageEquivalent sourceProcess targetProcess := by
  refine ⟨globalResponseImageEquivalent, ?_⟩
  intro equivalent
  exact not_currentViewResponseImageComplete equivalent.1

end BidirectionalGlobalResponseEquivalenceCounterexample

end Persistence.StructuralPersistence
